import { FigureType } from "./types";

export const initState = {
  cells: {
    11: { side: 2, type: FigureType.tower },
    12: { side: 2, type: FigureType.horse },
    13: { side: 2, type: FigureType.elephant },
    14: { side: 2, type: FigureType.quin },
    15: { side: 2, type: FigureType.king },
    16: { side: 2, type: FigureType.elephant },
    17: { side: 2, type: FigureType.horse },
    18: { side: 2, type: FigureType.tower },

    21: { side: 2, type: FigureType.pawn },
    22: { side: 2, type: FigureType.pawn },
    23: { side: 2, type: FigureType.pawn },
    24: { side: 2, type: FigureType.pawn },
    25: { side: 2, type: FigureType.pawn },
    26: { side: 2, type: FigureType.pawn },
    27: { side: 2, type: FigureType.pawn },
    28: { side: 2, type: FigureType.pawn },

    31: null,
    32: null,
    33: null,
    34: null,
    35: null,
    36: null,
    37: null,
    38: null,

    41: null,
    42: null,
    43: null,
    44: null,
    45: null,
    46: null,
    47: null,
    48: null,

    51: null,
    52: null,
    53: null,
    54: null,
    55: null,
    56: null,
    57: null,
    58: null,

    61: null,
    62: null,
    63: null,
    64: null,
    65: null,
    66: null,
    67: null,
    68: null,

    71: { side: 1, type: FigureType.pawn },
    72: { side: 1, type: FigureType.pawn },
    73: { side: 1, type: FigureType.pawn },
    74: { side: 1, type: FigureType.pawn },
    75: { side: 1, type: FigureType.pawn },
    76: { side: 1, type: FigureType.pawn },
    77: { side: 1, type: FigureType.pawn },
    78: { side: 1, type: FigureType.pawn },

    81: { side: 1, type: FigureType.tower },
    82: { side: 1, type: FigureType.horse },
    83: { side: 1, type: FigureType.elephant },
    84: { side: 1, type: FigureType.king },
    85: { side: 1, type: FigureType.quin },
    86: { side: 1, type: FigureType.elephant },
    87: { side: 1, type: FigureType.horse },
    88: { side: 1, type: FigureType.tower },
  },
  moveCells: [],
};
